services:
  backend:
    build: ./backend/vortex-admin-pro
    container_name: vortex-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres.boskcvexjyixxyhxczpe
      SPRING_DATASOURCE_PASSWORD: Diwooo1661@
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: vortex-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

